name: Build MOTG Cross-Platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  # This has to be done separately, else each and every os in the matrix will try to create their own tag
  prebuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_SHA: ${{ env.GITHUB_SHA }}
        with:
          tag_name: build-${{ github.run_id }}-${{ github.run_attempt }}
          release_name: Prerelease ${{ github.run_id }}-${{ github.run_attempt }}
          draft: false
          prerelease: true

  build:
    needs: [prebuild]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -U pyinstaller
    - name: Build with PyInstaller
      run: |
        pyinstaller -D -F -n generate -c -n MOTD-${{matrix.os}} ./generate.py
    - name: Get Newest Release Created
      id: latest_release
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        owner: oitsjustjose
        repo: MinecraftOreTextureGenerator
        excludes: draft
    - name: Create Release
      uses: actions/github-script@v2
      env:
        RELEASE_ID: ${{ steps.latest_release.outputs.id }}
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const fs = require('fs').promises;
          for (let file of await fs.readdir('./dist')) {
            console.log('uploading', `./dist/${file}`);
            await github.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: file,
              release_id: '${{env.RELEASE_ID}}',
              data: await fs.readFile(`./dist/${file}`)
            });            
          }
